### ISSUE TITLE
main_train_rl_agent_dqn.py : new tracks are not accepted 

### ISSUE THREAD

**Issue by p4ngui** [TUMFTM/race-simulation#3]
I found that I'm not able to train new tracks, this because in vse_supervised.py at init of the class, when preprocessor_cc.cat_dict is loaded from a pickle file, doesn't contains the new track (or i didn't find hot to doit), even if I use a base strategy only

**Comment by heilmeiera** [comment]
Sorry for the late reply, my notification settings were wrong so I did not get a mail that you opened an issue. You are right, the case that a new track should be trained was not handled so far. I just pushed a new commit to fix this issue (and several other stuff). Now, if the supervised VSE cannot be used for a new track, then either the reinforcement VSE, the base strategy VSE, or the real strategy VSE will be used.
